= VM GitOps Demo
Mohammed Salih <msalih@redhat.com>
:revnumber: 1
:revdate: 09-04-2025
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4
:icons: font
:source-highlighter: prettify
:data-uri:


== Prerequisites
- OpenShift Cluster with a RWX capable Storage
- OpenShift Virtualization should be enabled
- OpenShift GitOps should be installed from the operator hub
- CLI Tools - `oc`, `helm`, `argocd` and `git` should be available on your workstation to manage the application deployment

== Application deployment
=== Prepare
We are starting a new project called `banking-demo`. First, we will create a system group called `cluster-admins` in OpenShift. Next, we will add the `admin` user to the `cluster-admins` group. Finally, we will label the new namespace `banking-demo` so that the default GitOps (ArgoCD) instance running in `openshift-gitops` namesapce can manage the artifacts within this namespace. 

Now the `admin` user can login using SSO option of ArgoCD.

[source,yaml]
----
oc new-project banking-demo
oc adm groups new cluster-admins
oc adm groups add-users cluster-admins admin
oc label namespace banking-demo argocd.argoproj.io/managed-by=openshift-gitops
----
