= VM GitOps Demo
Mohammed Salih <msalih@redhat.com>
:revnumber: 1
:revdate: 17-12-2024
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4
:icons: font
:source-highlighter: prettify
:data-uri:

This repository demonstrates deploying a hybrid application on OpenShift using GitOps. It includes a VM-based web server, a containerized backend, and a database, showcasing how legacy and modern workloads can coexist.

It uses Helm charts for easily scaling virtual machines, but deployed through OpenShift GitOps (ArgoCD) rather than using the Helm in OpenShift. 

== Prerequisites
- OpenShift Cluster with a RWX capable Storage
- OpenShift Virtualization should be enabled
- OpenShift GitOps should be installed from the operator hub
- CLI Tools - `oc`, `helm`, `argocd` and `git` should be available on your workstation to manage the application deployment

== Application deployment
=== Prepare
We are starting a new project called `banking-demo`. First, we will create a system group called `cluster-admins` in OpenShift. Next, we will add the `admin` user to the `cluster-admins` group. Finally, we will label the new namespace `banking-demo` so that the default GitOps (ArgoCD) instance running in `openshift-gitops` namesapce can manage the artifacts within this namespace. 

Now the `admin` user can login using SSO option of ArgoCD.

[source,yaml]
----
oc new-project banking-demo
oc adm groups new cluster-admins
oc adm groups add-users cluster-admins admin
oc label namespace banking-demo argocd.argoproj.io/managed-by=openshift-gitops
----

=== Verify Helm variables
Make sure the values specified in `values.yaml` and `argo-application.yaml` are as desired.

.File: values.yaml
[source,yaml]
----
appDomain: apps.cnv.dxb.rhdxb.net
webserver:
  replicas: 2
  image: fedora
  image_ns: openshift-virtualization-os-images
  size: u1.small
  fineract_image: docker.io/fintecheando/web-app:master
 
database:
  image: mariadb:11.4
  storage: 10Gi
  storageclass: ocs-storagecluster-cephfs
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"

backend:
  image: docker.io/apache/fineract:latest
----

.File: argo-application.yaml
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mifos-x
spec:
  destination:
    name: ''
    namespace: banking-demo
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/linusali/vm-gitops-demo.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: webserver.replicas
          value: "3"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
----

Create the ArgoCD application
[source,bash]
----
oc apply -f argo-application.yaml
----

=== Monitor the appliation deployment
You can monitor the application deployment using CLI

[source,bash]
oc project banking-demo

==== List pods
Using CLI list the pods deployed in the current namespace `banking-demo`
[source,bash]
----
oc get pods 
----

==== List PVC
List Persistant storage deployed 
[source,bash]
----
oc get pvc
----

==== List Virtual Machines
List virtual machines deployed. Since the deployment is done in batches based on the dependencies, it might take a while before the virtual machine show up

[source,bash]
----
oc get vms
----

==== Access the application
Get the URL to access the deployed Mifo-X application's frontend
[source,bash]
----
oc get routes
----

== Interesting facts about this deployment

. Virtual machine can be scaled easily by modifying `webserver.replicas` count
. Virtual machine uses cloud-init scripts to instantiate itself
. Virtual machine uses Liveness and Readiness probes to monitor itself and reboot in case of any failure
. Virtual machine uses OpenShift's services and routes to expose itself to the external world 
